[build-system]
requires = ["maturin>=1.14,<2.0"]
build-backend = "builder_cb"
backend-path = ["."]

[project]
name = "randomness-kit"
description = "some tools about randomness calculation"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = [
    "maturin>=1.14.1",
]
authors = [{ "name" = "sbchild", "email" = "sbchild0@gmail.com" }]
license = { file = "LICENSE" }

[tool.maturin]
module-name = "randomness_kit._randomness_kit"
features = ["pyo3/extension-module", "pyo3/experimental-inspect"]
include = ["py.typed"]

[tool.maturin.generate-ci.github]
# Finally found: https://github.com/PyO3/maturin/blob/main/src/pyproject_toml.rs#L487
# but before_script_linux doesn't work
linux = { target = [{ arch = "x86_64", before_script_linux = "xxx" }] }
musllinux = { target = [{ arch = "x86_64", before_script_linux = "xxx" }] }
# args = "--generate-stubs" # stubs already exist 
# windows = {}
# macos = {}
# emscripten = {}
# android = {}
